@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User inputs add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command format is valid])
    :Parses and validates input into fields for person;

    if () then ([fields are valid])
    :Constructs Person object;
    :Constructs AddCommand object;
    :Returns back to LogicManager;
    :LogicManager executes AddCommand;
    if () then ([person is unique])
    :Insert person to PersonList;
    :Update UI;
    else ([else])
    :Display person already exist \nerror message;
    endif
    else ([else])
    :Display invalid \nfield error message;
    endif
else ([else])
:Display invalid \ncommand format error message;




endif
stop
@enduml
