@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes AddCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([input is valid])
    :Parse input into fields for person;
    :Constructs AddCommand object;
    :Returns back to LogicManager;
    :LogicManager executes AddCommand;
    :Insert person to PersonList;
    :Update UI;
else ([else])
:Display error message;

endif
stop
@enduml
