@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "c:Course" as Course MODEL_COLOR
participant ":Course" as CourseClass MODEL_COLOR
participant ":CourseUtil" as CourseUtil MODEL_COLOR
participant "p:Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute("add n/John \n p/81234567 \n c/CS2103T")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand\n("add n/John \n p/81234567 \n c/CS2103T")
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse\n("add n/John \n p/81234567 \n c/CS2103T")
activate AddCommandParser

AddCommandParser --> ParserUtil : parseCourses\n("CS2103T")
activate ParserUtil

ParserUtil --> ParserUtil : parseCourse\n("CS2103T")

ParserUtil -> CourseClass : isExistingCourseName("CS2103T")
activate CourseClass

CourseClass -> CourseUtil : contains\n("CS2103T")
activate CourseUtil
CourseUtil --> CourseClass
deactivate CourseUtil

CourseClass --> ParserUtil
deactivate CourseClass

create Course
ParserUtil -> Course : Course("CS2103T")
activate Course


Course --> ParserUtil : c
deactivate Course

ParserUtil --> AddCommandParser : sc
deactivate ParserUtil

create Person
AddCommandParser -> Person : Person("John", "81234567", ... , sc)
activate Person

Person --> AddCommandParser : p
deactivate Person

create AddCommand
AddCommandParser -> AddCommand : AddCommand(p)
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> AddressBookParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser
destroy AddCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addPerson(person)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
