@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCourseCommandParser" as FindCourseCommandParser LOGIC_COLOR
participant "fc:FindCourseCommand" as FindCourseCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":CourseContainsKeywordsPredicate" as CoursePredicate MODEL_COLOR
end box

[-> LogicManager : execute("findcourse MA2001")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("findcourse MA2001")
activate AddressBookParser

create FindCourseCommandParser
AddressBookParser -> FindCourseCommandParser
activate FindCourseCommandParser

FindCourseCommandParser --> AddressBookParser
deactivate FindCourseCommandParser

AddressBookParser -> FindCourseCommandParser : parse("MA2001")
activate FindCourseCommandParser


create FindCourseCommand
FindCourseCommandParser -> FindCourseCommand
activate FindCourseCommand

create CoursePredicate
FindCourseCommandParser -> CoursePredicate : "MA2001"
activate CoursePredicate

CoursePredicate --> FindCourseCommandParser
deactivate CoursePredicate

FindCourseCommand --> FindCourseCommandParser : fc
deactivate FindCourseCommand

FindCourseCommandParser --> AddressBookParser : fc
deactivate FindCourseCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCourseCommandParser -[hidden]-> AddressBookParser
destroy FindCourseCommandParser

AddressBookParser --> LogicManager : fc
deactivate AddressBookParser

LogicManager -> FindCourseCommand : execute()
activate FindCourseCommand

FindCourseCommand -> CoursePredicate : test(person)
activate CoursePredicate

CoursePredicate --> FindCourseCommand
deactivate CoursePredicate

FindCourseCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> FindCourseCommand
deactivate Model

create CommandResult
FindCourseCommand -> CommandResult
activate CommandResult

CommandResult --> FindCourseCommand
deactivate CommandResult

FindCourseCommand --> LogicManager : result
deactivate FindCourseCommand

[<--LogicManager
deactivate LogicManager
@enduml
