@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":TagUtil" as TagUtil MODEL_COLOR
participant ":Tag" as Tag MODEL_COLOR
participant ":TagType" as TagType MODEL_COLOR
end box

[-> LogicManager : execute("add n/John Doe p/12345678 t/Emergency")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add n/John Doe p/12345678 t/Emergency")
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse("add n/John Doe p/12345678 t/Emergency")
activate AddCommandParser


create Tag
AddCommandParser -> Tag
activate Tag

Tag -> TagType : setType("Emergency")
activate TagType

TagType --> Tag
deactivate TagType

Tag --> AddCommandParser
deactivate Tag

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> AddressBookParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser
destroy AddCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> TagUtil : canAddOrEditEmergencyTag(toAdd, currentPersonList)
activate TagUtil

TagUtil --> AddCommand
deactivate TagUtil

AddCommand -> Model : addPerson(toAdd)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand :result
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager :result
deactivate LogicManager
@enduml
