@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ThemeCommandParser" as ThemeCommandParser LOGIC_COLOR
participant "t:ThemeCommand" as ThemeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> MainWindow :
activate MainWindow

MainWindow -> LogicManager : execute\n("theme DARK")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("theme DARK")
activate AddressBookParser

create ThemeCommandParser
AddressBookParser -> ThemeCommandParser
activate ThemeCommandParser

ThemeCommandParser --> AddressBookParser
deactivate ThemeCommandParser

AddressBookParser -> ThemeCommandParser : parse("DARK")
activate ThemeCommandParser

create ThemeCommand
ThemeCommandParser -> ThemeCommand
activate ThemeCommand

ThemeCommand --> ThemeCommandParser : t
deactivate ThemeCommand

ThemeCommandParser --> AddressBookParser : t
deactivate ThemeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ThemeCommandParser -[hidden]-> AddressBookParser
destroy ThemeCommandParser

AddressBookParser --> LogicManager : t
deactivate AddressBookParser

LogicManager -> ThemeCommand : execute()
activate ThemeCommand

create CommandResult
ThemeCommand -> CommandResult
activate CommandResult

CommandResult --> ThemeCommand : result
deactivate CommandResult

ThemeCommand --> LogicManager : result
deactivate ThemeCommand

LogicManager --> MainWindow : result
deactivate LogicManager

MainWindow -> MainWindow : handleTheme\n("DARK")

[<--MainWindow
deactivate MainWindow
@enduml
